fixtures:
    repositories:
      #stdlib:  "git://github.com/puppetlabs/puppetlabs-stdlib"
      #concat:  "git://github.com/puppetlabs/puppetlabs-concat"
      stdlib:  "ssh://git@stash-dev.fx.srv.westpac.com.au:7999/pcm/puppetlabs-stdlib.git"
      concat:  "ssh://git@stash-dev.fx.srv.westpac.com.au:7999/pcm/puppetlabs-stdlib.git"
    symlinks:
        autossh: "#{source_dir}"
