fixtures:
    repositories:
      stdlib:  "git://github.com/puppetlabs/puppetlabs-stdlib"
      concat:  "git://github.com/puppetlabs/puppetlabs-concat"
    symlinks:
        autossh: "#{source_dir}"
